apiVersion: apps/v1
kind: Deployment
metadata:
  name: nana
  labels:
    app: cycle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cycle
  template:
    metadata:
      labels:
        app: cycle
    spec:
      containers:
        - name: cont2
          image: yaseenbasha/dim
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc2
spec:
  type: NodePort
  selector:
    app: cycle
  ports:
    - port: 80
      targetPort: 80

